### ISSUE TITLE
Search Bugs

### ISSUE THREAD

**Issue by Rrahmey** [learn-co-students/ios-team-green#1]
Cancel Should Only Bring Bar Down
Press Outside Bar Keyboard Should Go Down
Search Always Segues to Results View OR Displays "Nothing Found"

*SEARCH BUGS AND FLOW*
- [x] manual search entry very important
- [x] started crashing after fourth product bar scan t
- [x] froze when I tapped search

**Comment by amitc007** [comment]
done
